In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 10.1 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.9 MB 6.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 5.9 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 6.3 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.7 MB/s  0:00:01
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 7.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 7.1 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 7.0 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 7.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 7.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.1 MB/s  0:00:02
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.3

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 22, 21, 20],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"],
    "Marks": [85, 72, 91, 68, 78]
}
df=pd.DataFrame(data)

In [4]:
df.head()

  Student  Age Department  Marks
0       A   20        CSE     85
1       B   21         IT     72
2       C   22        CSE     91
3       D   21        ECE     68
4       E   20         IT     78

In [5]:
df.tail()

  Student  Age Department  Marks
0       A   20        CSE     85
1       B   21         IT     72
2       C   22        CSE     91
3       D   21        ECE     68
4       E   20         IT     78

In [7]:
df.shape

(5, 4)

In [9]:
df.columns

Index(['Student', 'Age', 'Department', 'Marks'], dtype='str')

In [12]:
df.dtypes

Student         str
Age           int64
Department      str
Marks         int64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [14]:
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   20.80000  78.800000
std     0.83666   9.364828
min    20.00000  68.000000
25%    20.00000  72.000000
50%    21.00000  78.000000
75%    21.00000  85.000000
max    22.00000  91.000000

In [16]:
df["Department"].unique()

<StringArray>
['CSE', 'IT', 'ECE']
Length: 3, dtype: str

In [17]:
df['Department'].nunique()

3

In [18]:
df['Department'].value_counts()

Department
CSE    2
IT     2
ECE    1
Name: count, dtype: int64

In [19]:
df.isnull().sum()

Student       0
Age           0
Department    0
Marks         0
dtype: int64

In [20]:
df['Marks'].max()

np.int64(91)

In [21]:
df[df['Marks']==df['Marks'].max()]

  Student  Age Department  Marks
2       C   22        CSE     91

In [22]:
df['Marks'] +=2

In [23]:
df

  Student  Age Department  Marks
0       A   20        CSE     87
1       B   21         IT     74
2       C   22        CSE     93
3       D   21        ECE     70
4       E   20         IT     80

In [24]:
df['Marks']=df['Marks']+2

In [25]:
df

  Student  Age Department  Marks
0       A   20        CSE     89
1       B   21         IT     76
2       C   22        CSE     95
3       D   21        ECE     72
4       E   20         IT     82

In [26]:
df['Marks']=df['Marks'].apply(lambda x:x+2)
print(df)

  Student  Age Department  Marks
0       A   20        CSE     91
1       B   21         IT     78
2       C   22        CSE     97
3       D   21        ECE     74
4       E   20         IT     84

In [28]:
df.loc[df['Student']=='E', 'Marks'] = df.loc[df['Student']=='E', 'Marks'] + 6
print(df)

  Student  Age Department  Marks
0       A   20        CSE     91
1       B   21         IT     78
2       C   22        CSE     97
3       D   21        ECE     74
4       E   20         IT     95